# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.ssh.forward_agent = true

  config.vm.define "local" , primary: true do |config|
    config.vm.network "private_network", ip: "10.0.0.2"
    # redis server
    config.vm.network :forwarded_port, guest: 3000, host: 3000

    config.vm.provider :virtualbox do |vb|
      vb.name = "blog-deploy"
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
  end
end
